### ISSUE TITLE
id parsing

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#13]
This didn't work:  

```
gdcp download -i https://docs.google.com/a/uw.edu/file/d/0B1vFU7eD_alGaXRiMk1qa1J6UzQ/edit?usp=drivesdk ./
```

Does work:

```
gdcp download -i 0B1vFU7eD_alGaXRiMk1qa1J6UzQ ./
```

**Comment by ctberthiaume** [comment]
Added support for that style of URL in d5b93a0. Where did you get that URL from? I haven't come across it. Looks like a Google Docs link but for a Google Drive file.

**Comment by ohthetrees** [comment]
I think that might be the style generated by insync. I'll ask them to update it to the more modern style.
