### ISSUE TITLE
problem parsing object id from url

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#17]
This does not work:

	gdcp download -i 'https://drive.google.com/a/uw.edu/file/d/xxxxFU7eD_alGd1JnQ0U2YmNKanc/view?usp=drivesdk' ./

This does:

	gdcp download -i 'https://drive.google.com/a/uw.edu/file/d/xxxxFU7eD_alGd1JnQ0U2YmNKanc' ./
(removed `/view?usp=drivesdk` from end of url)

**Comment by ctberthiaume** [comment]
Fixed in 9ced5ba
