### ISSUE TITLE
gdcp on sierra?  

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#22]
Following the install instructions in the README didn't yield a working install.

```
$ gdcp
Traceback (most recent call last):
  File "/usr/local/bin/gdcp", line 16, in <module>
    from pydrive.auth import GoogleAuth
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydrive/auth.py", line 15, in <module>
    from oauth2client.file import CredentialsFileSymbolicLinkError
ImportError: cannot import name CredentialsFileSymbolicLinkError
```

```
$ pip search oauth2client
courseraoauth2client (0.0.1)  - An OAuth2 client for the Coursera App Platform.
oauth2client (4.0.0)          - OAuth 2.0 client library
  INSTALLED: 4.0.0 (latest)

```

```
sudo port install -f py27-oauth2client
[snip]
$ gdcp
usage: gdcp [-h] {version,list,download,upload,transfer} ...
```

**Comment by ctberthiaume** [comment]
I've successfully installed dependencies and run on Sierra with Anaconda Python and Homebrew Python. I haven't tested with Macports, which is what it looks like you're using. I'll try to find a machine with Macports to test on, but in the meantime I wonder if the `pip` command you used to install oauth2client was actually tied to the same Python installation that Macports uses or if it's tied to the system Python.

**Comment by ctberthiaume** [comment]
I think this is probably a macports / Python configuration issue rather than a Sierra / gdcp / pydrive issue. Just tested with a fresh Sierra  + macports installation and I wasn't able to recreate the error. I installed the python27 and py27-pip ports and made them my path defaults.

```
sudo port install python27 py27-pip
sudo port select --set pip pip27
sudo port select --set python python27
pip install pydrive backoff
```
