### ISSUE TITLE
Doesn't work for me. Errors...

### ISSUE THREAD

**Issue by shillshocked** [ctberthiaume/gdcp#23]
After running gdcp, I get:

  File "/home/phoenix/bin/gdcp", line 146
    except OSError, IOError:
                  ^
SyntaxError: invalid syntax

After correcting line 146 to:
"except (OSError, IOError) as e:"

I get:
  File "/home/phoenix/bin/gdcp", line 434
    print json.dumps(self.metadata)
             ^
SyntaxError: invalid syntax

**Comment by ctberthiaume** [comment]
Thanks for reporting this. gdcp only supports Python 2 and based on the syntax errors here it looks like the default `python` in your environment is Python 3. I've updated the shebang line to explicitly ask for Python 2 and added some more text in the README about Python 2 vs 3 errors (dfa8c17d). You may need to reinstall `pydrive` and `backoff` with the Python 2 `pip`, probably called `pip2` on your system.
