### ISSUE TITLE
Is there a version of gdcp that will run with Python 2.6.6 ?

### ISSUE THREAD

**Issue by eeny999** [ctberthiaume/gdcp#24]
Hi there,
I know this is not really an issue, and the doco clearly says that this needs  Python 2.7. Unfortunately the shared server I work on is  Python 2.6.6 and I have no control over updating it. Are there any versions of gdcp that will run on that version of Python?
Thanks in advance.

**Comment by ctberthiaume** [comment]
I haven't tested with Python 2.6 and don't have any plans to support it. My suggestion would be to install Python 2.7 in your home directory. Assuming you have gcc available this should work. Or you can install a compatible version of Anaconda to get a local Python 2.7.

**Comment by eeny999** [comment]
Thanks Chris. Will try it.
