### ISSUE TITLE
is this project still supported?

### ISSUE THREAD

**Issue by chhh** [ctberthiaume/gdcp#26]

**Comment by ctberthiaume** [comment]
As you may have inferred from the delayed response this project is no longer supported. The code might be useful as a guide for using the Google Drive Python API, but for command-line use I would recommend [rclone](https://github.com/ncw/rclone) instead. It can do everything `gdcp` can do and more. The only feature I would say is missing is ownership transfer and support for object IDs. `rclone` requires paths which, at least for my use case, is slightly more inconvenient, but not enough to outweigh its other benefits.
