### ISSUE TITLE
ImportError: No module named apiclient.errors

### ISSUE THREAD

**Issue by kkew3** [ctberthiaume/gdcp#28]
> Traceback (most recent call last):
>   File "$HOME/bin/gdcp", line 3, in <module>
>     import apiclient.errors
> ImportError: No module named apiclient.errors

Note: "$HOME/bin/gdcp" is where I place the binary.

This error occurs **from time to time**, and I haven't found any pattern when it happens yet. Is there any way to solve? Thanks!

**Comment by komposure** [comment]
Did you install this using a virtual environment? This is likely to do with dependencies not being found, or if you have permission issues when installing those dependencies.

**Comment by komposure** [comment]
I think "apiclient.errors" is from `google-api-python-client` which is a subdependency of `pydrive`. That's likely where your error is. Try debugging by checking if the dependencies exist with `pip list`

**Comment by kkew3** [comment]
Thank you for your response! I checked with `pip list` and it does exist. I install it globally. I'm kind of suspecting that the problem occurs whenever I'm in a virtualenv where `google-api-python-client` is not included. While `gdcp` is under `/usr/bin` such that I get access to it, the lack of `google-api-python-client` in virtualenv stops it from running. I'll verify this hypothesis.

**Comment by kkew3** [comment]
Sorry for the late response. It seems that I was in a virtualenv where `google-api-python-client` is not included.
