### ISSUE TITLE
No module named apiclient.errors

### ISSUE THREAD

**Issue by ar8372** [ctberthiaume/gdcp#33]
```
    import apiclient.errors
ImportError: No module named apiclient.errors
```

This is the error I get, when I run gdcp using following code:=> ~/bin/gdcp 

when I look into gdcp content it is like:- 

```
#!/usr/bin/env python2.7

import apiclient.errors
import apiclient.http
from argparse import ArgumentDefaultsHelpFormatter
from argparse import ArgumentParser

```

and the issue is in the line: `import apiclient.errors`

Please feel free to ask any further query to understand the issue. 
**note: I am using it to connect google drive to a remote ssh server linux machine.**

**Comment by ctberthiaume** [comment]
Thanks for reporting the error. I'm not maintaining this project anymore. In fact, it's still based on Python 2 which has been end-of-lifed for over two years. I would recommend using [rclone](https://rclone.org/) if you need CLI access to Google Drive.
